version: '3'

services:
  torrentmonitor:
    container_name: torrentmonitor-test
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./data/torrents:/data/htdocs/torrents
      - ./data/db:/data/htdocs/db
      - ./data/logs:/data/htdocs/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PHP_TIMEZONE=America/Detroit
      - CRON_TIMEOUT=0 * * * *
      - PHP_MEMORY_LIMIT=512M 
