name: Notify about PR or Issue

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      url:
        description: 'URL to include in the notification (e.g. a PR link)'
        required: false
        type: string

jobs:
  notify-on-telegram:
    runs-on: ubuntu-latest
    env:
      telegram_to: ${{ secrets.TELEGRAM_TO }}
    steps:
      - name: Skip Telegram notification
        shell: bash
        if: ${{ env.telegram_to == '' }}
        run: |
          echo "Telegram SECRETS not defined, skip Telegram notification"

      - name: Notify on Telegram
        uses: appleboy/telegram-action@v1.1.1
        if: ${{ env.telegram_to != '' }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          disable_web_page_preview: true
          message: |
            New ${{ github.event_name == 'workflow_dispatch' && 'pull request' || github.event_name }} created

            See details:
            ${{ github.event_name == 'pull_request' && github.event.pull_request.html_url || github.event_name == 'issues' && github.event.issue.html_url || inputs.url }}
